/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Oct-2017 01:20:06 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS csdetteam_pkdetteam_seq
;

DROP SEQUENCE IF EXISTS csteam_pkteam_seq
;

DROP SEQUENCE IF EXISTS csuser_pkuser_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS csdetteam CASCADE
;

DROP TABLE IF EXISTS csDiagrama CASCADE
;

DROP TABLE IF EXISTS csteam CASCADE
;

DROP TABLE IF EXISTS csuser CASCADE
;

/* Create Tables */

CREATE TABLE csdetteam
(
	pkdetteam integer NOT NULL   DEFAULT NEXTVAL(('"csdetteam_pkdetteam_seq"'::text)::regclass),
	fkteam integer NOT NULL,
	fkintegrante integer NOT NULL,
	estado char(1) NULL
)
;

CREATE TABLE csDiagrama
(
	pkdiagrama integer NOT NULL,
	nombre varchar(50) NOT NULL,
	fkteam integer NOT NULL
)
;

CREATE TABLE csteam
(
	pkteam integer NOT NULL   DEFAULT NEXTVAL(('"csteam_pkteam_seq"'::text)::regclass),
	codigo varchar(25) NULL,
	descripcion varchar(50) NULL,
	fkpropietario integer NOT NULL,
	estado char(1) NULL
)
;

CREATE TABLE csuser
(
	pkuser integer NOT NULL   DEFAULT NEXTVAL(('"csuser_pkuser_seq"'::text)::regclass),
	nickname varchar(50) NULL,
	nombreCom varchar(50) NULL,
	apellidoCom varchar(50) NULL,
	password varchar(50) NULL,
	email varchar(50) NULL,
	authkey varchar(50) NULL,
	accesstoken varchar(50) NULL,
	estado char(1) NULL,
	pkteam integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE csdetteam ADD CONSTRAINT PK_csdetteam
	PRIMARY KEY (pkdetteam)
;

CREATE INDEX IXFK_csdetteam_csteam ON csdetteam (fkteam ASC)
;

ALTER TABLE csDiagrama ADD CONSTRAINT PK_csDiagrama
	PRIMARY KEY (pkdiagrama)
;

CREATE INDEX IXFK_csDiagrama_csteam ON csDiagrama (fkteam ASC)
;

ALTER TABLE csteam ADD CONSTRAINT PK_csteam
	PRIMARY KEY (pkteam)
;

CREATE INDEX IXFK_csteam_csuser_02 ON csteam (fkpropietario ASC)
;

ALTER TABLE csuser ADD CONSTRAINT PK_csuser
	PRIMARY KEY (pkuser)
;

CREATE INDEX IXFK_csuser_csteam ON csuser (pkteam ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE csdetteam ADD CONSTRAINT FK_csdetteam_csteam
	FOREIGN KEY (fkteam) REFERENCES csteam (pkteam) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE csDiagrama ADD CONSTRAINT FK_csDiagrama_csteam
	FOREIGN KEY (fkteam) REFERENCES csteam (pkteam) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE csteam ADD CONSTRAINT FK_csteam_csuser_02
	FOREIGN KEY (fkpropietario) REFERENCES csuser (pkuser) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE csdetteam_pkdetteam_seq INCREMENT 1 START 1
;

CREATE SEQUENCE csteam_pkteam_seq INCREMENT 1 START 1
;

CREATE SEQUENCE csuser_pkuser_seq INCREMENT 1 START 1
;
