/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 31-Ene-2018 09:39:37 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "csautoincremento_pkautoincremento_seq"
;

DROP SEQUENCE IF EXISTS "cstype_pktype_seq"
;

DROP SEQUENCE IF EXISTS "cscolumna_pkcolumna_seq"
;

DROP SEQUENCE IF EXISTS "cstabla_pktabla_seq"
;

DROP SEQUENCE IF EXISTS "csuser_pkuser_seq"
;

DROP SEQUENCE IF EXISTS "csteam_pkteam_seq"
;

DROP SEQUENCE IF EXISTS "csdetteam_pkdetteam_seq"
;

DROP SEQUENCE IF EXISTS "csdiagrama_pkdiagrama_seq"
;

DROP SEQUENCE IF EXISTS "csrelacion_pkrelacion_seq"
;

DROP SEQUENCE IF EXISTS "cscardinalidad_pkcardinalidad_seq"
;

/* Drop Tables */

DROP TABLE IF EXISTS "csAutoIncremento" CASCADE
;

DROP TABLE IF EXISTS "csType" CASCADE
;

DROP TABLE IF EXISTS "csColumna" CASCADE
;

DROP TABLE IF EXISTS "csTabla" CASCADE
;

DROP TABLE IF EXISTS "csuser" CASCADE
;

DROP TABLE IF EXISTS "csteam" CASCADE
;

DROP TABLE IF EXISTS "csdetteam" CASCADE
;

DROP TABLE IF EXISTS "csDiagrama" CASCADE
;

DROP TABLE IF EXISTS "csRelacion" CASCADE
;

DROP TABLE IF EXISTS "csCardinalidad" CASCADE
;

/* Create Tables */

CREATE TABLE "csAutoIncremento"
(
	"pkAutoIncremento" integer NOT NULL DEFAULT nextval(('"csautoincremento_pkautoincremento_seq"'::text)::regclass),
	"fkColumna" integer NOT NULL,
	"startNum" integer NULL,
	"increment" integer NULL,
	"seqName" varchar(25)	 NULL
)
;

CREATE TABLE "csType"
(
	"pkType" integer NOT NULL DEFAULT nextval(('"cstype_pktype_seq"'::text)::regclass),
	"nombre" varchar(25)	 NOT NULL,
	"size_bool" boolean NOT NULL,
	"scale_bool" boolean NOT NULL
)
;

CREATE TABLE "csColumna"
(
	"pkColumna" integer NOT NULL DEFAULT nextval(('"cscolumna_pkcolumna_seq"'::text)::regclass),
	"fkTabla" integer NOT NULL,
	"fkType" integer NOT NULL,
	"nombre" varchar(25)	 NOT NULL,
	"size" integer NULL,
	"scala" integer NULL,
	"primaryKey" boolean NOT NULL,
	"notNull" boolean NOT NULL
)
;

CREATE TABLE "csTabla"
(
	"pkTabla" integer NOT NULL DEFAULT nextval(('"cstabla_pktabla_seq"'::text)::regclass),
	"nombreTabla" varchar(25)	 NOT NULL,
	"fkUserCreate" integer NOT NULL,
	"fechaCreate" date NOT NULL,
	"fkDiagrama" integer NOT NULL
)
;

CREATE TABLE "csuser"
(
	"pkuser" integer NOT NULL DEFAULT nextval(('"csuser_pkuser_seq"'::text)::regclass),
	"nickname" varchar(50)	 NULL,
	"nombreCom" varchar(50)	 NULL,
	"apellidoCom" varchar(50)	 NULL,
	"password" varchar(50)	 NULL,
	"email" varchar(50)	 NULL,
	"authkey" varchar(50)	 NULL,
	"accesstoken" varchar(50)	 NULL,
	"estado" char(1)	 NULL
)
;

CREATE TABLE "csteam"
(
	"pkteam" integer NOT NULL DEFAULT nextval(('"csteam_pkteam_seq"'::text)::regclass),
	"codigo" varchar(25)	 NULL,
	"descripcion" inet NULL,
	"fkpropietario" integer NOT NULL,
	"estado" char(1)	 NULL
)
;

CREATE TABLE "csdetteam"
(
	"pkdetteam" integer NOT NULL DEFAULT nextval(('"csdetteam_pkdetteam_seq"'::text)::regclass),
	"fkteam" integer NOT NULL,
	"fkintegrante" integer NOT NULL,
	"estado" char(1)	 NULL
)
;

CREATE TABLE "csDiagrama"
(
	"pkdiagrama" integer NOT NULL DEFAULT nextval(('"csdiagrama_pkdiagrama_seq"'::text)::regclass),
	"nombre" varchar(50)	 NOT NULL,
	"fkteam" integer NOT NULL
)
;

CREATE TABLE "csRelacion"
(
	"pkRelacion" integer NOT NULL DEFAULT nextval(('"csrelacion_pkrelacion_seq"'::text)::regclass),
	"nameRelacion" varchar(25)	 NULL,
	"fkTablaFrom" integer NOT NULL,
	"fkTablaTo" integer NOT NULL,
	"fkCardinalidadFrom" integer NOT NULL,
	"fkCardinalidadTo" integer NOT NULL
)
;

CREATE TABLE "csCardinalidad"
(
	"pkCardinalidad" integer NOT NULL DEFAULT nextval(('"cscardinalidad_pkcardinalidad_seq"'::text)::regclass),
	"descripcion" varchar(25)	 NULL,
	"from" varchar(10)	 NULL,
	"to" varchar(10)	 NULL
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE "csautoincremento_pkautoincremento_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "cstype_pktype_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "cscolumna_pkcolumna_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "cstabla_pktabla_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "csuser_pkuser_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "csteam_pkteam_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "csdetteam_pkdetteam_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "csdiagrama_pkdiagrama_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "csrelacion_pkrelacion_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "cscardinalidad_pkcardinalidad_seq" INCREMENT 1 START 1
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "csAutoIncremento" ADD CONSTRAINT "PK_csAutoIncremento"
	PRIMARY KEY ("pkAutoIncremento")
;

CREATE INDEX "IXFK_csAutoIncremento_csColumna" ON "csAutoIncremento" ("fkColumna" ASC)
;

ALTER TABLE "csType" ADD CONSTRAINT "PK_csType"
	PRIMARY KEY ("pkType")
;

ALTER TABLE "csColumna" ADD CONSTRAINT "PK_csColumna"
	PRIMARY KEY ("pkColumna")
;

CREATE INDEX "IXFK_csColumna_csTabla" ON "csColumna" ("fkTabla" ASC)
;

CREATE INDEX "IXFK_csColumna_csType" ON "csColumna" ("fkType" ASC)
;

ALTER TABLE "csTabla" ADD CONSTRAINT "PK_csTabla"
	PRIMARY KEY ("pkTabla")
;

CREATE INDEX "IXFK_csTabla_csDiagrama" ON "csTabla" ("fkDiagrama" ASC)
;

CREATE INDEX "IXFK_csTabla_csuser" ON "csTabla" ("fkUserCreate" ASC)
;

ALTER TABLE "csuser" ADD CONSTRAINT "PK_csuser"
	PRIMARY KEY ("pkuser")
;

ALTER TABLE "csteam" ADD CONSTRAINT "PK_csteam"
	PRIMARY KEY ("pkteam")
;


ALTER TABLE "csdetteam" ADD CONSTRAINT "PK_csdetteam"
	PRIMARY KEY ("pkdetteam")
;

CREATE INDEX "IXFK_csdetteam_csteam" ON "csdetteam" ("fkteam" ASC)
;

CREATE INDEX "IXFK_csdetteam_csuser" ON "csdetteam" ("fkintegrante" ASC)
;

ALTER TABLE "csDiagrama" ADD CONSTRAINT "PK_csDiagrama"
	PRIMARY KEY ("pkdiagrama")
;

CREATE INDEX "IXFK_csDiagrama_csteam" ON "csDiagrama" ("fkteam" ASC)
;

ALTER TABLE "csRelacion" ADD CONSTRAINT "PK_csRelacion"
	PRIMARY KEY ("pkRelacion")
;

CREATE INDEX "IXFK_csRelacion_csCardinalidad" ON "csRelacion" ("fkCardinalidadFrom" ASC)
;

CREATE INDEX "IXFK_csRelacion_csCardinalidad_02" ON "csRelacion" ("fkCardinalidadTo" ASC)
;

CREATE INDEX "IXFK_csRelacion_csTabla" ON "csRelacion" ("fkTablaFrom" ASC)
;

CREATE INDEX "IXFK_csRelacion_csTabla_02" ON "csRelacion" ("fkTablaTo" ASC)
;

ALTER TABLE "csCardinalidad" ADD CONSTRAINT "PK_csCardinalidad"
	PRIMARY KEY ("pkCardinalidad")
;

/* Create Foreign Key Constraints */

ALTER TABLE "csAutoIncremento" ADD CONSTRAINT "FK_csAutoIncremento_csColumna"
	FOREIGN KEY ("fkColumna") REFERENCES "csColumna" ("pkColumna") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csColumna" ADD CONSTRAINT "FK_csColumna_csTabla"
	FOREIGN KEY ("fkTabla") REFERENCES "csTabla" ("pkTabla") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csColumna" ADD CONSTRAINT "FK_csColumna_csType"
	FOREIGN KEY ("fkType") REFERENCES "csType" ("pkType") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csTabla" ADD CONSTRAINT "FK_csTabla_csDiagrama"
	FOREIGN KEY ("fkDiagrama") REFERENCES "csDiagrama" ("pkdiagrama") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csTabla" ADD CONSTRAINT "FK_csTabla_csuser"
	FOREIGN KEY ("fkUserCreate") REFERENCES "csuser" ("pkuser") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csteam" ADD CONSTRAINT "FK_csteam_csuser_02"
	FOREIGN KEY ("fkpropietario") REFERENCES "csuser" ("pkuser") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csdetteam" ADD CONSTRAINT "FK_csdetteam_csteam"
	FOREIGN KEY ("fkteam") REFERENCES "csteam" ("pkteam") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csdetteam" ADD CONSTRAINT "FK_csdetteam_csuser"
	FOREIGN KEY ("fkintegrante") REFERENCES "csuser" ("pkuser") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csDiagrama" ADD CONSTRAINT "FK_csDiagrama_csteam"
	FOREIGN KEY ("fkteam") REFERENCES "csteam" ("pkteam") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csRelacion" ADD CONSTRAINT "FK_csRelacion_csCardinalidad"
	FOREIGN KEY ("fkCardinalidadFrom") REFERENCES "csCardinalidad" ("pkCardinalidad") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csRelacion" ADD CONSTRAINT "FK_csRelacion_csCardinalidad_02"
	FOREIGN KEY ("fkCardinalidadTo") REFERENCES "csCardinalidad" ("pkCardinalidad") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csRelacion" ADD CONSTRAINT "FK_csRelacion_csTabla"
	FOREIGN KEY ("fkTablaFrom") REFERENCES "csTabla" ("pkTabla") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "csRelacion" ADD CONSTRAINT "FK_csRelacion_csTabla_02"
	FOREIGN KEY ("fkTablaTo") REFERENCES "csTabla" ("pkTabla") ON DELETE No Action ON UPDATE No Action
;
