/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Oct-2017 04:34:22 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS csdetteam_pkdetteam_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS csdetteam CASCADE
;

/* Create Tables */

CREATE TABLE csdetteam
(
	pkdetteam integer NOT NULL   DEFAULT NEXTVAL(('"csdetteam_pkdetteam_seq"'::text)::regclass),
	fkteam integer NOT NULL,
	fkintegrante integer NOT NULL,
	estado char(1) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE csdetteam ADD CONSTRAINT PK_csdetteam
	PRIMARY KEY (pkdetteam)
;

CREATE INDEX IXFK_csdetteam_csteam ON csdetteam (fkteam ASC)
;

CREATE INDEX IXFK_csdetteam_csuser ON csdetteam (fkintegrante ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE csdetteam ADD CONSTRAINT FK_csdetteam_csteam
	FOREIGN KEY (fkteam) REFERENCES csteam (pkteam) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE csdetteam ADD CONSTRAINT FK_csdetteam_csuser
	FOREIGN KEY (fkintegrante) REFERENCES csuser (pkuser) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE csdetteam_pkdetteam_seq INCREMENT 1 START 1
;
