/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Oct-2017 05:53:24 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS csdiagrama_pkdiagrama_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS csDiagrama CASCADE
;

/* Create Tables */

CREATE TABLE csDiagrama
(
	pkdiagrama integer NOT NULL   DEFAULT NEXTVAL(('"csdiagrama_pkdiagrama_seq"'::text)::regclass),
	nombre varchar(50) NOT NULL,
	fkteam integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE csDiagrama ADD CONSTRAINT PK_csDiagrama
	PRIMARY KEY (pkdiagrama)
;

CREATE INDEX IXFK_csDiagrama_csteam ON csDiagrama (fkteam ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE csDiagrama ADD CONSTRAINT FK_csDiagrama_csteam
	FOREIGN KEY (fkteam) REFERENCES csteam (pkteam) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE csdiagrama_pkdiagrama_seq INCREMENT 1 START 1
;
