/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Oct-2017 02:19:56 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS csuser_pkuser_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS csuser CASCADE
;

/* Create Tables */

CREATE TABLE csuser
(
	pkuser integer NOT NULL   DEFAULT NEXTVAL(('"csuser_pkuser_seq"'::text)::regclass),
	nickname varchar(50) NULL,
	nombreCom varchar(50) NULL,
	apellidoCom varchar(50) NULL,
	password varchar(50) NULL,
	email varchar(50) NULL,
	authkey varchar(50) NULL,
	accesstoken varchar(50) NULL,
	estado char(1) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE csuser ADD CONSTRAINT PK_csuser
	PRIMARY KEY (pkuser)
;


/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE csuser_pkuser_seq INCREMENT 1 START 1
;
